alias ...='cd ../..'
alias ..='cd ..'
alias cat1='cat $(lt1)'
alias cp='cp -iv'
alias dc='docker compose'
alias dnd="bash $SCRIPTS/do_not_disturb_toggle.sh"
alias dx='docker compose exec'
alias ec='emacsclient -nc'
alias f="bash $SCRIPTS/search-firefox-history.sh"
alias gb='git branch --list'
alias gc='git checkout'
alias gd='git diff'
alias gs='git status'
alias less1='less -S $(lt1)'
alias ll='ls -AlhF --color=always --group-directories-first'
alias ls='ls -AF --color=always --group-directories-first'
alias lt1='ls -Frt | tail -1'
alias lt='ls -AlhFrt --color=always'
alias mv='mv -iv'
alias o='open'
alias psg='ps aux | grep --color -i'
alias s='for i in {1..15}; do echo; done' # Create some space in the terminal
alias tmuxat='tmux a -t'
alias vim='nvim'
alias zz='pmset sleepnow'
