# Get editor completions based on the config schema
"$schema" = 'https://starship.rs/config-schema.json'

# Prompt format
format = '$directory$git_branch$git_state$git_metrics$git_status$fill$line_break$character'

# Inserts a blank line between shell prompts
add_newline = true

[directory]
truncation_length = 10
style = 'bold white'

[git_branch]
style = 'bold white'

[git_state]
disabled = false

[git_metrics]
disabled = true

[git_status]
disabled = true

[fill]
symbol = '-'
style = 'white'
