# Get editor completions based on the config schema
"$schema" = 'https://starship.rs/config-schema.json'

# Prompt format
# format = '$all$fill$directory$line_break$character'
format = '$directory$git_branch$git_commit$git_state$git_metrics$git_status$fill$all$line_break$character'

# Inserts a blank line between shell prompts
add_newline = true

[fill]
symbol = ' '

[git_branch]
style = 'bold fg:#dbbc7f'

[git_status]
disabled = true

[directory]
truncation_length = 10
style = 'bold fg:#8da101'

[aws]
disabled = true

[docker_context]
disabled = true
